# Config k?t n?i port
server:
  port: 8080
  servlet:
    context-path: /identity
# Config k?t n?i t?i DB
spring:
  datasource:
#    url: 'jdbc:mysql://localhost:3306/identity_service'
    #Nếu trong config ko set giá trị thì sẽ dùng giá trị default sau dấu :
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
# Config JPA để tự động tạo DB trong thực tế phải tạo bằng SQL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "but75kvdatab3cqvos454bs761fb6i0y"
  valid-duration: 20 # in second
  refreshable-duration: 120 # in second